baseurl                 = "http://remotekieran.com/"               # Your domain name. Must end with "/"
languageCode            = "en-us"
title                   = "Kieran Kilbride-Singh – Remote Writer and Marketer"
theme                   = "sam"
pygmentsStyle           = "manni"                     # https://help.farbox.com/pygments.html
pygmentsCodefences      = true
# googleAnalytics       = ""             # Tracking code, eg. "UA-111111111-1"

[params]
    dateform            = "Mon Jan 02, 2006"
    dateformfull        = "Mon Jan 2 2006 15:04:05 EST"
    favicon             = "/sam.png"
    homepage            = "home"                        # What to call the home page link
    galleryFolder       = "images/"                     # Where you've put your images, after "/content/gallery/"
    clickablePhotos     = true                          # Allow links to the full size images
    footerText          = ""

# Metadata
    description         = "Kieran is a writer and marketer with five years experience marketing B2B tech products. He's worked remotely for most of that time."            # Max 160 characters show in search results
    twitterCard         = "summary_large_image"         # Card value “summary”, “summary_large_image”, “app”, or “player”
    primaryImage        = "/sam.png"                     # Image that shows on Twitter cards and OpenGraph links

[[params.mainMenu]]
    link = "/about"
    text = "who is kieran?"

[[params.mainMenu]]
    link = "/work"
    text = "previous work"