baseurl                  = "https://remotekieran.com/"           # Your domain name. Must end with "/"
languageCode             = "en-us"
defaultContentLanguage   = "en"
isMultilingual           = false
title                    = "Kieran Kilbride-Singh | Marketing leader focused on PLG GTM strategy for developers"
theme                    = "sam"
pygmentsStyle            = "monokai"                        # https://help.farbox.com/pygments.html
pygmentsCodefences       = true
# googleAnalytics        = ""                               # Tracking code, eg. "UA-111111111-1"

[params]
    dateform             = "Jan 02 2006"
    dateformfull         = "Jan 02 2006 15:04:05 EST"
    favicon              = "kks.png"
    homepage             = "home"                           # What to call the home page link
    footerText           = "Current base: Bangkok, Thailand"

# Metadata for Open Graph and Twitter
    description          = "Kieran is a marketing leader and digital nomad. For ten years he's driven awareness and adoption of developer tools and infrastructure with data at their core."               # Max 160 characters show in search results
    images               = ["kks.png"]                       # Image that shows on Twitter cards and Open Graph links to the site
    title                = "Kieran Kilbride-Singh | Marketing leader focused on PLG GTM strategy for developers""

[[params.mainMenu]]
    link = "/about"
    text = "about"

[[params.mainMenu]]
    link = "/blog"
    text = "blog"

[[params.mainMenu]]
    link = "/work"
    text = "work"

[imaging]
    quality = 75